location = /adr/ruleset.yaml {
    return 301 https://gitdocumentatie.logius.nl/publicatie/api/adr/2.1.0/media/linter.yaml;
}
location = /adr/2.1/ruleset.yaml {
    return 301 https://gitdocumentatie.logius.nl/publicatie/api/adr/2.1.0/media/linter.yaml;
}
